replicaCount: 3
image:
  repository: ghcr.io/lonedone/rev-test
  tag: latest
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 80
env:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "ExamplePassword"
  DB_HOST: ""
  DB_NAME: "users_db"
  DB_PORT: 5432
  NODE_ENV: production
