apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-load-balancer-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aws-load-balancer-controller
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: aws-load-balancer-controller
          image: amazon/aws-alb-ingress-controller:v2.4.5
          args:
            - --cluster-name={{ .Values.clusterName }}
            - --aws-region={{ .Values.region }}
            - --aws-vpc-id={{ .Values.vpcId }}
